# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robokassa', '0001_initial'),
        ('minecraft', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='minecraftuser',
            name='last_payment_notification',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='robokassa.SuccessNotification', verbose_name='Последний платёж'),
        ),
    ]
