# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-03 08:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('minecraft', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinecraftUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(verbose_name='Баланс')),
                ('status', models.CharField(choices=[('Оплачено', 'Оплачено'), ('Не оплачено', 'Не оплачено')], max_length=10, verbose_name='Статус подписки на сервер')),
                ('avatar', models.FileField(upload_to='avatars/users/', verbose_name='Аватар игрока')),
                ('active_until', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания подписки')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт пользователя')),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
            },
        ),
    ]
