# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-03 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minecraft', '0002_minecraftuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='minecraftuser',
            name='registered_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Зарегистрировался'),
        ),
        migrations.AlterField(
            model_name='minecraftuser',
            name='balance',
            field=models.IntegerField(verbose_name='Количество кредитов'),
        ),
    ]
