# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 11:44
from __future__ import unicode_literals

import app.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minecraft', '0002_auto_20170707_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minecraftuser',
            name='avatar',
            field=models.FileField(default='avatars/default/default_avatar.jpg', upload_to=app.functions.user_directory_path, verbose_name='Аватар игрока'),
        ),
    ]
