# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-03 07:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('minecraft', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampNews',
            fields=[
                ('minecraftnews_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='minecraft.MinecraftNews')),
            ],
            bases=('minecraft.minecraftnews',),
        ),
    ]
