# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampuser',
            name='avatar',
            field=models.FileField(default='avatars/default/default_avatar.jpg', upload_to='avatars/users/', verbose_name='Аватар игрока'),
        ),
    ]
