# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-03 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minecraft', '0002_minecraftuser'),
        ('samp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampUser',
            fields=[
                ('minecraftuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='minecraft.MinecraftUser')),
            ],
            bases=('minecraft.minecraftuser',),
        ),
    ]
