# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-03 08:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samp', '0002_sampuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sampnews',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='sampuser',
            options={'verbose_name': 'Игрок', 'verbose_name_plural': 'Игроки'},
        ),
    ]
